doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
        profiling_collect_backtrace: '%kernel.debug%'
        use_savepoints: true

          #        default_connection: default
        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)

#        connections:
#            default:
#                driver: pdo_mysql
#                use_savepoints: true
#                dbname: '%env(resolve:MYSQL_DATABASE)%'
#                host: '%env(resolve:DATABASE_HOST)%'
#                port: '%env(resolve:DATABASE_PORT)%'
#                user: '%env(resolve:MYSQL_USER)%'
#                password: '%env(resolve:MYSQL_PASSWORD)%'
#                server_version: '8.0.33'
#                profiling_collect_backtrace: '%kernel.debug%'
#                charset: 'utf8mb4'
                #DATABASE_URL="mysql://bruno:test@db:3306/crossfit_test?serverVersion=8.0.33&charset=utf8mb4":

    orm:
        auto_generate_proxy_classes: true
        enable_lazy_ghost_objects: true
        report_fields_where_declared: true
        validate_xml_mapping: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
#        identity_generation_preferences:
#            Doctrine\DBAL\Platforms\PostgreSQLPlatform: identity
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App

when@test:
    doctrine:
        dbal:
            # "TEST_TOKEN" is typically set by ParaTest
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            proxy_dir: '%kernel.build_dir%/doctrine/orm/Proxies'
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
