services:
  db:
    container_name: crossfit-pgsql
    image: postgres:${POSTGRES_VERSION:-16}-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-crossfit}
      # You should definitely change the password in production
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-!ChangeMe!}
      POSTGRES_USER: ${POSTGRES_USER:-app}
    healthcheck:
      test: [ "CMD", "pg_isready", "-d", "${POSTGRES_DB:-crossfit}", "-U", "${POSTGRES_USER:-app}" ]
      timeout: 5s
      retries: 5
      start_period: 60s
    volumes:
      - "db_app:/var/lib/postgresql/data:rw"
    ports:
      - "5432:5432"
    networks:
      - crossfit
  php:
    container_name: crossfit-php
    build:
      context: .docker/php
      args:
        TIMEZONE: Europe/Madrid
    volumes:
      - .:/var/www/symfony:cached
    networks:
      - crossfit
  nginx:
    container_name: crossfit-nginx
    build:
      context: .docker/nginx
    volumes:
      - .:/var/www/symfony:cached
    ports:
      - 80:80
    networks:
      crossfit:
        aliases:
          - admin.crossfit.local
    env_file:
      - .docker/.env.nginx
  mailer:
    container_name: crossfit-mailcatcher
    image: schickling/mailcatcher
    ports: ["1025", "1080"]

volumes:
  db_app:

networks:
  crossfit:
    driver: bridge
