MovementCluster:
  type: object
  config:
    fields:
      id: ID!
      repetitions: Int!
      repUnit: RepUnitEnum!
      implements: "[Implement]!"
      movement: Movement!
      movementDetail: MovementDetail
