MovementCluster:
  type: object
  config:
    fields:
      id: ID!
      repetitions: Int!
      movement: Movement!
      implementIntensityAdjustmentValue: Float
      movementDetailIntensityUnit: ImplementTypeOfAdjustableMeasureUnit
      repUnit: MeasureUnitEnum!
      implements: "[Implement]!"
