Query:
  type: object
  config:
    fields:
      workouts:
        type: '[Workout]'
        resolve: '@=query("App\\Api\\Graphql\\Resolver\\Query\\WorkoutsResolver::resolve")'
      workoutsByName:
        type: '[Workout]!'
        resolve: '@=query("App\\Api\\Graphql\\Resolver\\Query\\WorkoutsResolver::getWorkoutsByName", args["name"])'
        args:
          name: String!
      workoutsByWorkoutOrigin:
        type: '[Workout]!'
        resolve: '@=query("App\\Api\\Graphql\\Resolver\\Query\\WorkoutsResolver::getWorkoutByWorkoutOrigin", args["workoutOriginId"])'
        args:
          workoutOriginId: String!
      workout:
        type: Workout!
        resolve: '@=query("App\\Api\\Graphql\\Resolver\\Query\\WorkoutResolver::resolve", args["id"])'
        args:
          id: String!
      workoutOriginNames:
        type: "[String!]!"
        resolve: '@=query("App\\Api\\Graphql\\Resolver\\Query\\WorkoutOriginsNameResolver::resolve")'
      workoutOriginsByWorkoutOriginsName:
        type: '[WorkoutOrigin]!'
        resolve: '@=query("App\\Api\\Graphql\\Resolver\\Query\\WorkoutOriginsResolver::getWorkoutOriginsByName", args["workoutOriginName"])'
        args:
          workoutOriginName: String!
