fixtures_list:
    path: /fixtures
    defaults:
        _controller: 'App\Controller\FixturesController'
fixture:
    path: /fixtures/{slug}
    controller: App\Controller\FixturesController::getOneFixtureData